"""IDK

Revision ID: 69e995b4b3dd
Revises: d9ccf7ca4fb7
Create Date: 2023-10-31 18:22:54.043888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e995b4b3dd'
down_revision: Union[str, None] = 'd9ccf7ca4fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('user_fk', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_fk'], ['users.chat_id'], name=op.f('fk_channels_user_fk_users')),
    sa.PrimaryKeyConstraint('channel_id', name=op.f('pk_channels')),
    sa.UniqueConstraint('channel_id', name=op.f('uq_channels_channel_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channels')
    # ### end Alembic commands ###
