services:
  redis:
    container_name: 'redis'
    image: 'redis:7.0.12-alpine'
    ports:
      - '6379:6379'
    restart: 'unless-stopped'
    volumes:
      - '~/${VOLUMES_DIR}/redis-assets:/assets'
  postgres:
    container_name: 'postgres'
    image: 'postgres:15.3-alpine'
    ports:
      - '5432:5432'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - 'src/.env'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  nats:
    container_name: 'nats'
    image: 'nats:2.9.19-alpine'
    restart: 'unless-stopped'
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    command: 'nats-server -js -sd /nats-assets/assets'
  src:
    container_name: 'src'
    build:
      context: .
      dockerfile: buildfiles/Dockerfile
    stop_signal: SIGTERM
    restart: 'unless-stopped'
    depends_on:
      - nats
      - redis
      - postgres
volumes:
  postgres_data: